ALTER TABLE findings ADD COLUMN IF NOT EXISTS plain_english TEXT;
ALTER TABLE findings ADD COLUMN IF NOT EXISTS suggested_fix JSONB;
ALTER TABLE findings ADD COLUMN IF NOT EXISTS attack_path JSONB;
ALTER TABLE findings ADD COLUMN IF NOT EXISTS bounty_estimate_usd BIGINT DEFAULT 0;
ALTER TABLE findings ADD COLUMN IF NOT EXISTS confidence REAL;
